{% set name = "diffpy.srmise" %}
{% set version = "0.6.1rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test.pypi.io/packages/source/d/diffpy_srmise/diffpy_srmise-{{ version }}.tar.gz
  sha256: 09d5f9107262d732530cc6817fee5a817324e2f9ee5c3575a72440d4cf3dbb74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >=3.10
    - numpy
    - scipy
    - matplotlib-base

test: 
  requires:
    - pip
    - pytest
  imports:
    - diffpy.srmise
  source_files:
    - tests
  commands:
    - pytest

about:
  home: https://github.com/diffpy/diffpy.srmise/
  summary: A Pyhton package for peak extraction and peak fitting for atomic pair distribution functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    A Pyhton package for peak extraction and peak fitting for atomic pair distribution functions.
  doc_url: https://diffpy.github.io/diffpy.srmise/
  dev_url: https://github.com/diffpy/diffpy.srmise/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
